[package]
name = "krust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "*"
dashmap = "4.0.2"
fxhash = "0.2.1"
rayon = "*"

[dev-dependencies]
insta     = "1.14.1"