[package]
name = "krust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "*"
itertools = "0.10.1"
rayon = "*"
reduce = "0.1"
rustc-hash = "1.1.0"
